[build-system]
requires = ["setuptools>=80", "wheel>=0.45", "setuptools_scm>=9.2"]
build-backend = "setuptools.build_meta"

[project]
name = "requsim"
description = "A simulation framework for quantum repeaters"
readme = "README.md"
authors = [
    { name = "Julius Wallnöfer" }
]
license = {file = "LICENSE"}
dependencies = [
    "numpy>=2.3.5",
    "pandas>=2.3.3"
]
classifiers=[
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Physics",
    "Intended Audience :: Science/Research",
]
keywords = [
    "quantum information",
    "quantum information theory",
    "quantum communication",
    "quantum repeater"
]
requires-python = ">=3.11"
dynamic = ["version"]

[project.urls]
homepage = "https://github.com/jwallnoefer/requsim"

[project.optional-dependencies]
test = ["pytest>=9.0.2"]
docs = [
    "sphinx",
    "autodocsumm",
    "recommonmark",
    "sphinx-rtd-theme",
    "requests>=2.32.5",
    "certifi>=2025.11.12",
    "Pygments>=2.19.2",
    "idna>=3.11",
    "urllib3>=2.6.2",
    "Jinja2>=3.1.6"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
write_to = "src/requsim/version.py"
local_scheme = "no-local-version"
